### PR TITLE
Various "minor" changes (4)

### PR DESCRIPTION
**Pull request by Hans5958**
Sequel to #1432. This is yet another set of changes. I suggest viewing [the commits tab](https://github.com/placeAtlas/atlas/pull/1428/commits) to see (and check) the changes made. Anyone is welcome to test it, as well as giving feedback.

Some highlights:

- Add schema-based validation (7398fd39c690fbc0cb1490f441faac49a696f1c5)
  This is only used on the validation workflow due to the relatively long time it take. This could be added on `aformatter.py` if wanted to.
- Use tqdm for progress bar, and write directly (it made it way faster) (0a232273f97f3d73f6aaca2d8f4f7362587edceb)
- Use -1 as placeholder ID for new entries (689007a153432fbd2247759f85c7bfc55f211c84)
  0 could meant as the very first entry, index-wise, whereas -1 have a more obvious meaning of an invalid ID.
- Per-entry patches (cdd21f9)
  See https://github.com/placeAtlas/atlas/pull/1435#issuecomment-1593256303

### CODE REVIEW

**Comment by Codixer** [comment]
Atlas.json conflict @Hans5958, please resolve.

**Review by Codixer — CHANGES_REQUESTED** [review]
Meep

**Comment by Hans5958** [comment]
Wilco. I am quite busy so expect in around 24h.

**Comment by Hans5958** [comment]
An experiemental of per-entry patches has been implemented to reduce dependency on Reddit, especially on creating new entries.

Contributors now can submit patches by creating separate files on `data/patches` for each submission. Instead of having temporary JSON file generated from `redditcrawl.py`, it will create the relevant patches instead. These patches will be merged by `merge_out.py`.

Contributors can submit patches by creating a new `.json` patch on `data/patches`, or use the included tool, `create_patch.py`, that assists the script user on creating a patch.

This is inspired from how changeset works on merging the information.

This gives the following advantages:
- Contributors can update the Atlas data through GitHub, and only one person have to merge it to the main Atlas data. All without dealing with the potential conflicts to the main `atlas.json`.
- Numerical IDs can be used again. This is either a pro or a con. I saw this as a pro, but in any way this is a better way to support both sources, next to a generating meaningless, random string.
- Reducing the dependency of Reddit. Even though we can somehow work the way through the Reddit API, some people didn't want to use Reddit as a boycott, or just for the fact that the subreddit is now closed for a while. With this, people can use multiple avenues, all without creating a overhead to the developers/staff members.

TODO

- [ ] Add info to `CONTRIBUTING.md` (how to create patches, how to merge, etc)
- [ ] Add info on "Create New Entry" modal
- [ ] Use the position index instead of the id for sorting by `Oldest` and `Newest`

**Review by Codixer — APPROVED** [review]

**Pull request merged**
