### PR TITLE
Removed incorrect entry

### PR DESCRIPTION
**Pull request by Rikri4009**

### CODE REVIEW

**Comment by AnonymousRandomPerson** [comment]
What makes this entry incorrect? There are no other entries for this art, and this user's profile pic matches what is displayed in the art?

**Comment by Rikri4009** [comment]
It's my PFP (Rikri#4009 on Discord) - I haven't added an entry since I don't exactly have anything to say about it.

**Comment by AnonymousRandomPerson** [comment]
If you don't have anything to say about it, you can leave the description blank and change the name to your name.

**Comment by Rikri4009** [comment]
I don't really want to do that, but if I _have_ to I'll write something there.

**Comment by AnonymousRandomPerson** [comment]
The entry shouldn't be removed when it is known what it is. The atlas is a living document, so any simple description will do for now, and you can revise it later if you think of a better one.

**Comment by Rikri4009** [comment]
Did that work?

**Comment by AnonymousRandomPerson** [comment]
Your latest commit created another `atlas.json` at the project root instead of updating the existing one.

**Comment by Rikri4009** [comment]
whoops, that was dumb

**Pull request merged**
