### PR TITLE
Bottom bar with time travel

### PR DESCRIPTION
**Pull request by ProstoSanja**
Allows to view canvas at different points in time, by using the slider at the bottom. + reworks the bottom sheet.

See https://deploy-preview-483--place-atlas.netlify.app/ for example

### CODE REVIEW

**Comment by ProstoSanja** [comment]
image
⏳

**Comment by ProstoSanja** [comment]
Ready to Merge

**Comment by nico-abram** [comment]
This seems to share all the current metadata for all points in time. Is that intended?

**Comment by Watrmeln** [comment]
time travel bar is kindof iffy on mobile and hard to control.

**Comment by ProstoSanja** [comment]
Ready to Merge when issues with bandwidth are resolved

**Pull request merged**
