### PR TITLE
egypt flag changes

### PR DESCRIPTION
**Pull request by maro2323**
egypt flag area change, egyptian unity symbol description change, ankh position update

### CODE REVIEW

**Comment by nico-abram** [comment]
Is it intended that this is touching 20+ lines?

**Comment by maro2323** [comment]
> Is it intended that this is touching 20+ lines?

I barely know what I'm doing so trust me I do not know what that means lol

**Comment by nico-abram** [comment]
@maro2323 could you look at this page https://github.com/placeAtlas/atlas/pull/900/files and tell me if all those changes are changes you want to do? red=removed and green=added

**Comment by maro2323** [comment]
@nico-abram the only changes I meant to do were in these lines, 147,148, 2853-2855, 6836-6843

**Comment by nico-abram** [comment]
@maro2323 could you close this one and send a new one? Maybe delete your fork (settings>red button at the bottom) and re-fork to sync up your fork's cleanup with the real one

**Pull request closed without merging**
