### PR TITLE
Updating Information for ID tx7q3r

### PR DESCRIPTION
**Pull request by velkog**
As this post on reddit indicates, the information  and borders provided for this entry are inaccurate. 

https://www.reddit.com/r/placeAtlas2/comments/txiko7/id_tx7q3r_showing_incorrect_information_here_is/

Creating the changes suggested from the reddit thread with a few minor edits in this PR.

### CODE REVIEW

**Comment by TrevorSayre** [comment]
I believe this should be against the `cleanup` branch.

**Comment by velkog** [comment]
> I believe this should be against the `cleanup` branch.

Got it, changed to the `cleanup` branch, thanks!

**Comment by TrevorSayre** [comment]
Looks like it now includes commits from other users, may need a rebase.

**Comment by ab-gh** [comment]
Please rebase this commit to include only your changes

**Comment by velkog** [comment]
Sorry about that, I suck at git

**Pull request closed without merging**
