### PR TITLE
Yume Nikki polish

### PR DESCRIPTION
**Pull request by Sparing134**
Changes(all Yume Nikki related):
-Removed 2 outdated submissions
-Improved/updated text/links in several submissions
-Improved borders in most submissions

### CODE REVIEW

**Comment by memmam** [comment]
This PR has unintentional changes and is likely to be closed; I am talking to the person who made it and am going to issue a fixed PR very shortly, just waiting on them to send me the relevant information.

**Comment by AnonymousRandomPerson** [comment]
This undoes a lot of other edits. Please rebase/merge the current cleanup branch so you're up to date.

**Comment by memmam** [comment]
@AnonymousRandomPerson yeah, this seems to be a repeated issue with people following my pull request guide on the Discord, either they'll wait a really long time after forking to make their changes and not fetch first, or they'll have other commits merged in while they're working because of how fast the repo is updating and not know what to do.

I feel like that's kind of my fault for making the process accessible to people who may not necessarily understand how Git works, and I'm sorry if it's increased your workload.

**Comment by memmam** [comment]
Just filed a new, fixed PR, see #944.

**Pull request closed without merging**
