### PR TITLE
Force highlight when entry heading is clicked

### LINKED ISSUE #1372: Unable to click entry header link twice
If you click the header of an entry, where the link icon is, the entry is added to the url with the ID and timeline position, as expected.

However, if you click the same entry header again it does not update. A side effect of this is that if you have the entry already linked to in the url and you change the timeline position it's not possible to update it if you click the entry header.

### PR DESCRIPTION
**Pull request by Hans5958**
Resolves #1372

### CODE REVIEW

**Comment by mxdanger** [comment]
I found an issue where if you click the entry heading it correctly sets the time however if you change the time and click on the link again it switches your time back to what it was originally instead of updating.

**Comment by AnonymousRandomPerson** [comment]
There are a bunch of commits on this PR unrelated to the change. Merge/rebase as needed to fix the commit history.

**Review by AnonymousRandomPerson — CHANGES_REQUESTED** [review]
The timeline position isn't added to the URL as is, so I'm not sure what this issue is meant to fix. Asked for clarification on the original issue (https://github.com/placeAtlas/atlas/issues/1372).

**Comment by Hans5958** [comment]
> I found an issue where if you click the entry heading it correctly sets the time however if you change the time and click on the link again it switches your time back to what it was originally and it does not update the url.

Right, the reason is same as why the entry box aren't updated when the time changes.

1. The behavior is that changing the time would keep the box on, even if the entry didn't exist at the point of time. Because of that,...
2. The way it works is that the entry box contents would be kept until it is updated by moving the mouse on the canvas. Because of that,...
3. When you change the time and you click the header, since the link stays the same, it would warp you back to the time when the box is created.

So with the way it works, that is not an issue.

> Apparently the original issue is asking to add the timeline position to the URL. That functionality doesn't exist yet.

https://deploy-preview-1384--place-atlas.netlify.app/#txibq9/1

**Comment by AnonymousRandomPerson** [comment]
I see, I thought the intention was to change the URL whenever scrubbing the timeline, but the URL only changes when clicking the permalink button.

The fix in this PR appears to be different than what #1372 asks for. My understanding is that this sequence of actions should occur:
1. Go to a previous timeline position.
2. Click the permalink button in an entry.
3. URL updates with entry ID and timeline position.
4. Go to a different timeline position.
5. Click the permalink button.
6. URL updates with the new timeline position.

What happens in master:
5. Click the permalink button.
6. Nothing happens.

What happens in this PR:
5. Click the permalink button.
6. URL stays the same and the timeline position reverts to what it was when permalink was previously clicked.

**Review by AnonymousRandomPerson — CHANGES_REQUESTED** [review]
Fix the issue in the way requested by issue #1372.

**Comment by Hans5958** [comment]
You misunderstand the real.

The issue on #1384 is that **you can't click the header twice**. This is the **main issue** and has been fixed with this PR. The issue that you discussed right now ([this comment](https://github.com/placeAtlas/atlas/pull/1384#issuecomment-1200273263)) is **a byproduct** of [_having the entry box to be kept in view when scrubbing the timeline_](https://github.com/placeAtlas/atlas/pull/1384#issuecomment-1214146954), and it is **unrelated** to the main issue.

So, clicking the header would **update it so it goes to the time that the link has**, and this PR **forces it to update**, without minding the hash change.

If you want to discuss _what happens with the entry box when the timeline is changed_, I suggest to create a separate issue for discussion.  This PR would maintain the status quo.

**Comment by AnonymousRandomPerson** [comment]
That does not make sense to me. Why would it be useful to click on the link button to basically imitate the browser refresh button?

I am merely going off of my interpretation of #1372, which evidently differs from yours. Perhaps @mxdanger can chime in with the intended meaning of that ticket.

**Comment by Hans5958** [comment]
The same reason as why would anyone click the header in the first place. You can move to an entry by yourself, so why do that in the first place.

Keep in mind that this also includes any other change, including zooming and moving, and others. Clicking it once would reset the camera and the time, and it would only work only once, you wouldn't want that, and this is the issue.

**Comment by AnonymousRandomPerson** [comment]
I suppose that has a use, though based on @mxdanger's [comment](https://github.com/placeAtlas/atlas/pull/1384#issuecomment-1200273263), the timeline position appears to be what the issue refers to. If you can get that confirmation, we can move forward.

**Comment by mxdanger** [comment]
It should be straight forward to the user. If you change the time to 140 on the slider and click the link you should get the time and the entry ID. If you then change the time again in the slider and click the link you should get the updated time and ID.

**Comment by Codixer** [comment]
@mxdanger @AnonymousRandomPerson 
What is the state of this PR?

**Comment by AnonymousRandomPerson** [comment]
The PR does not fix #1372 in the way expected by the ticket. Before it can be merged, the PR should change the fix to match @mxdanger's and my comments.

**Pull request closed without merging**
