### PR TITLE
LBP duplicated entry removed and fixed the other LBP entry's description.

### PR DESCRIPTION
**Pull request by Ezoiar**
LBP duplicated entry removed and fixed the other LBP entry's description.

### CODE REVIEW

**Comment by Ezoiar** [comment]
PS: This is a 14 hours old file, I didn't bother to change the other things to latest so please only apply it at **twmd9s** and **100463**.

**Comment by ab-gh** [comment]
> PS: This is a 14 hours old file, I didn't bother to change the other things to latest so please only apply it at **twmd9s** and **100463**.

Please rebase this branch to the latest /cleanup branch

**Review by ab-gh — CHANGES_REQUESTED** [review]
Please rebase this branch to only include your edit

**Comment by ab-gh** [comment]
This PR has been closed. Please reopen when you make the required changes.

**Pull request closed without merging**
