### PR TITLE
New center algorithm

### PR DESCRIPTION
**Pull request by fabi321**
this is the version from Mapbox, just to see how well it performs. It definitely needs improvements as of now. I'm going to include the atlas.json, but it will be excluded once the pr is ready to be merged.

### CODE REVIEW

**Comment by Hans5958** [comment]
Maybe format it later so you can do it together with #1231.

**Review by Codixer — CHANGES_REQUESTED** [review]
The atlas.json has been completly borked up, make sure this is changed
image

**Comment by Hans5958** [comment]
stefda's has no LICENSE, but https://github.com/Twista/python-polylabel/blob/master/polylabel/__init__.py has MIT on it.

**Comment by fabi321** [comment]
As I said, I want to include the atlas changes during development, and reset atlas.json to it's original state after all work is done. The current 'borking up' is just that the script converted it to LF instead of CRLF due to me having linux (and #1165 not being merged)

**Comment by fabi321** [comment]
While there are definitely still tweaks needed here and there, this version is the first that is somewhat visually pleasing

**Comment by fabi321** [comment]
https://deploy-preview-1235--place-atlas.netlify.app/?id=twpyje: While this center might be the one that has all borders the furthest away, I think we should find a balance between "pole of inaccessibility" and "centroid". And while I changed the algorithm now to also account for the centroid, it clearly isn't enough

**Comment by fabi321** [comment]
It's actually so good now, that I'm open to discuss any points that look odd. Even aforementioned points look good now. Feel free to throw id's at me and I might fix their edge cases

**Comment by fabi321** [comment]
For some reason unknown to me, the atlas.json on netlify doesn't get updated (as of now). You might need to run this locally to browse it

**Comment by fabi321** [comment]
As I now reverted all changes my to atlas.json, you need to run the script locally in order to see the changes by it.

**Comment by Hans5958** [comment]
If possible, could you rebase it so the atlas commits are removed from your PR?

**Comment by fabi321** [comment]
It has been more than just dropping those commits, as I comitted atlas changes along with code changes. I think it is fixed now

**Comment by Hans5958** [comment]
Hmm okay at least you did the rebase

**Comment by Hans5958** [comment]
Also download https://cdn.jsdelivr.net/npm/tinyqueue@2.0.3/tinyqueue.min.js and put it in the repo?

**Comment by fabi321** [comment]
> Also download https://cdn.jsdelivr.net/npm/tinyqueue@2.0.3/tinyqueue.min.js and put it in the repo?

Does this make any difference? Or is it only about consistency? I don't really have any strong opinions on it.

**Comment by Hans5958** [comment]
I don't know, something something Netlify preprocessing magic

**Comment by Hans5958** [comment]
I think this should be on the remaster, just so the huge changes won't happen multiple times, but what do you think?

**Comment by fabi321** [comment]
I agree that this is better had on remaster, as there probably will be braking changes

**Comment by Hans5958** [comment]
Go point the PR to `remaster` and I'll merge it for you.

**Pull request merged**
