### PR TITLE
Major UI redesign

### LINKED ISSUE #1320: Website redesign

### PR DESCRIPTION
**Pull request by mxdanger**
Closes #1320, part of #1314. Needs to be updated to be feature parity with remaster branch before merging.

- Accessibility fix: Closes #1223

Normal mode:
Dark mode screenshot
Light mode screenshot

Edit object mode:
Dark mode screenshot

About page:
Dark mode screenshot

### CODE REVIEW

**Comment by Hans5958** [comment]
Nice work, dude! Although there are some things I need to point out, which hopefully we can address together. 

Main points:

1. Some parts have missing light mode styles. Pardon me beacuse light theme is my daily driver, but if we can support light theme, I think it's best to fully support it. Some of these are the zoom controls and the time slider, or maybe that's by design/your intention. I don't know. If that's the design of Bootstrap then it's fine.
2. For the entry information when drawing, I think I would take a "quite radical turn" and just write "r/" for the text, just like how Reddit does. Also we can have multiple websites. We should also consider whether description is required. Last time it doesn't, and it works.

Picky stuff (just so I won't forget, excluding those that we will done to achieve parity):

1. Scale the logo so it looks bigger?
2. Add margin on the timeline tooltip.
3. Button of Entries List should be hidden when drawing
4. There is a bug when clicking the Entries List/Draw menu too much would bug the Atlas position
5. Let's try match the loading overlay with the modern design (and maybe the colors)
6. I'm still thinking on making the entry title to black, but dunno...
7. The shift of the atlas should match the animation of the entry list (I'm certain we can do this)

**Comment by Hans5958** [comment]
Here's what I mean with this number 4 on the picky stuff.

recording


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Firefox 100.0 on Windows 10
Viewport:  1920 x 918 @1x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1334--place-atlas.netlify.app%2F&os=Windows&os_version=10&browser=Firefox&browser_version=100.0&resolution=1920x918&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-1334--place-atlas.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=626106d8bfea5b000948bd1a&commentID=6261337bdcc9ce4811cd7678&resolution=resolved)

**Comment by mxdanger** [comment]
Number 4 is just inevitable due to the fact that you're canceling the transition mid-way though. However, I was able to minimize the jankyness by only adding the listHidden class *after* the animation is finished so aborting the transition won't leave behind or add the class when it shouldn't be there.

**Comment by Hans5958** [comment]
I think you can turn off the transition by overriding the CSS using `transition: none !important`. I'm still certain that we can make the canvas also animated, I think.

**Comment by mxdanger** [comment]
### Todo
- [ ] Fix reset button that doesn't clear the object info inputs.
- [ ] Add a warning prompt when clicking reset to prevent accidental activation.
- [ ] Fix contents of timeline tooltip that become hidden off screen on narrow displays.
- [ ] Update loading overlay with Bootstrap styling.
- [ ] Fix export entry "Post Direct to Reddit" button has weird styling issues on iOS Safari.
- [ ] Fix the amount of vertical space in the entries list side bar on displays that aren't tall.
- [ ] Add on overflow of object info hover list, at the bottom let the user know they can click the map to lock their selection. 
  - #820
- [ ] Add icons to the variant dropdown. Just like it is in the period edit mode.
- [ ] #1318
 
### Bucket list
- [ ] Update the shift of the atlas to match the animation of the entry list slide over.

**Comment by Hans5958** [comment]
Ideally the search box on the explore button should be hidden

**Comment by Hans5958** [comment]
Later this should be adjusted when it is an edit.

image

**Review by Hans5958 — APPROVED** [review]
LGTM. I think there are some things that needs to be changed by a little bit, but I think it's fine for now.

**Pull request merged**
