### PR TITLE
de-revert entry for Niko

### PR DESCRIPTION
**Pull request by prezmop**
PR #1271 has accidentally reverted entry 000097 (Niko) to an earlier version. This PR de-reverts it.
Note: entry twug6y could also have been affected. However it didn't have any recent changes, so it's fine.

### CODE REVIEW

**Comment by prezmop** [comment]
@mxdanger , please be more careful.

**Comment by mxdanger** [comment]
> @mxdanger , please be more careful.

This seems to just be a merge conflict that was incorrectly resolved. There's nothing I could have done to be more careful.

**Comment by mxdanger** [comment]
However, you shouldn't revert the path, as the change I made should be correct.

**Comment by prezmop** [comment]
> It seems like you reverted the path too. If it's only the description that was incorrectly merged then I'd suggest you update your commit to only change the description.

both description and path were accidentally reverted

> Edit: Actually I don't remember touching that ID or doing any edits in that area so the new path could be the better version.

you accidentally touched it in when editing 000096 in commit bd851f6486466067bdb7d4543fad1eca82584d16

**Comment by mxdanger** [comment]
Ah I see where how that happened, Its when I accidentally formatted two entries into one line and then I split it back into two in another commit. However I’m not sure why this merge conflict wasn’t initially resolved with the correct version.

**Pull request merged**
