### PR TITLE
Changes to id twv6o6

### PR DESCRIPTION
**Pull request by Querez**
The original description was lackluster and had grammatical errors, so I sought to fix that. I also updated the path to be more accurate.

### CODE REVIEW

**Comment by Querez** [comment]
Please only look at twv6o6. Everything else just looks different because they all became outdated by the time I submitted my changes. That isn't my fault

**Comment by nico-abram** [comment]
Please resubmit with only changes to what you want to change

**Comment by Querez** [comment]
> Please resubmit with only changes to what you want to change

I *am*, I have no idea what you mean. Am I supposed to *only* include the one single line I want to make changes to in the atlas.json file, deleting all other lines? Because that was *not* specified in the step-by-step process provided in the Discord server, so I had no way of knowing.

**Comment by Querez** [comment]
@nico-abram Sorry for mention, I have no idea if you'll respond if I don't do it

**Comment by Querez** [comment]
Maybe not

**Comment by nico-abram** [comment]
@Querez sorry I got an email and just saw it

If you you want to, join the discord with the button on the website and ping me in #support 

I mean in https://github.com/placeAtlas/atlas/pull/889/files there are changes to a lot of things, not just twv6o6

**Pull request closed without merging**
