### PR TITLE
cleanup, removing & merging duplicate entries, etc

### PR DESCRIPTION
**Pull request by GitFincy**
Merged 3 entries for Nina en Nijntje, requested by `Wouter#4142` in thread https://discord.com/channels/960791635342524496/963065658864717846

Improved twrvna path
Improved twr2vr path
Made both descriptions more consistent

### CODE REVIEW

**Comment by GitFincy** [comment]
merged two Grachtenpanden (Canal House) entries

**Comment by GitFincy** [comment]
merged 4 'The Starry Night' entries

**Comment by GitFincy** [comment]
merged two Christiania entries

**Comment by ab-gh** [comment]
Thank you for all the work!

**Pull request merged**
