### PR TITLE
Various "minor" changes

### LINKED ISSUE #1353: Calculate initial zoom based on entry dimensions
There are some entries that are too small, it needs to be zoomed in, and there are some entries that are too big, in needs to be zoomed out. There is only one zoom for all of it, so should be a way to calculate the initial zoom based on the dimensions of the entry.

### LINKED ISSUE #1368: Dynamic default period range on creation
When creating a new period, the default position of the start and end range should be set to the user's current timeline position instead of the variant config default. This would allow for a more intuitive way of adding periods and immediately start drawing.

### PR DESCRIPTION
**Pull request by Hans5958**
Hello, 2023! Sorry for the dormancy. Here are a variety of minor changes that I put in a single branch/PR. Anyone is welcome to test it, as well as giving feedback.

While there are loads of changes, I have make sure the each different changes is separates in each commit with a clear description. You can check [the commits tab](https://github.com/placeAtlas/atlas/pull/1425/commits) if you want to check the exact changes.

Some highlights:
- Fix stretching due to Netlify's new badges (bf9903f674345edbb5efba8c4936614dfa31c47e)
- Fix Qodana code quality issues (e.g. e274864edb7eb277119d69190dc07c36775d958c)
- Improve CONTRIBUTING.md to be more substantive, based on [the Reddit post](https://www.reddit.com/r/placeAtlas2/comments/tu203o/how_to_contribute/), the remaster changes, and includes code contributions (e.g. 98445110820ec6cf6d30d479628bf1c421c5babf, 3652700a954056539ade20416f5c7c3b7bebcb9a)
- Improve README and issue templates (f598da3be9ee4f6ad22ea07c23151c930c8c373e)
- Calculate zoom based on entry dimensions (73c65233fa388d5a5dfee5c575d508ab4ad3a9cb, resolves #1353)
- Use URL-based state (period and variations) more effectively (e.g. f006df8f693aa127a4d0aa129bfac1c5994f1b75, cec161ef97cc6ada9bacd81cfcfe295c04078370 resolves #1368)
- Configure ID-based sorting to also use length (339432ff14e278b2c82087543ec9ea29ca1f70d8)
- Put entry name when submitting using "Post Direct to Reddit" button (e.g. 4a2ddf5432baacf7528cb61d7d4628963f40e781)
- Various refactoring and tidying on various aspects such as atlas engine, tools scripts, and workflow

### CODE REVIEW

**Comment by Hans5958** [comment]
#1423 and #1424 have been merged on this branch/PR to streamline the process.

**Comment by Hans5958** [comment]
This PR now resolves #1353. Zoom are now calculated based on the entry's dimensions, with a cap of 4x just so it doesn't get too close and confusing.

**Comment by Hans5958** [comment]
This PR now resolves #1368. Links/button for editing and return from editing now uses the current state (period and variation). The current URL now updates when moving periods.

**Comment by Hans5958** [comment]
By the way, anything on this branch is ready to review. If there is more I would just add it in the future, either in another time or branch.

**Review by Codixer — APPROVED** [review]

**Comment by AnonymousRandomPerson** [comment]
No issues from me at the moment.

**Comment by mxdanger** [comment]
I tried out the preview and found no issues with the new changes.

**Comment by Hans5958** [comment]
Something I should mentioned a while back: The process for exporting an entry for submissions has been improved. Other than handling for the 40000 text limit, it also put the entry title on the post when clicking the "Post Direct to Reddit" button.

I also added the emojis before it. What am I thinking is that it is fine, since the flairs would be replaced anyway. It is not a necessity, though, and submitting it manually still works (it would still check the flair anyway). Let me know if this is fine.

image

image

**Comment by Hans5958** [comment]
A significant thing that I wanted to stress again: [CONTRIBUTING.md](https://github.com/Hans5958/place-atlas/blob/live-love-life/CONTRIBUTING.md) has been updated significantly, and the page is now linked instead, replacing the outdated Reddit post. Everyone is invited to read (and suggest) of the page before it is merged.

https://github.com/Hans5958/place-atlas/blob/live-love-life/CONTRIBUTING.md

**Pull request merged**
