### PR TITLE
fix: update right subreddit and description for chained woman in xuzhou

### PR DESCRIPTION
**Pull request by jincha89**
r/china_place is the actual subreddit that created the Chained Woman in Xuzhou artwork, r/china_irl members later on joined the r/china_place subreddit to work on this artwork, as well the discord group later disbanded as most of our members are from Mainland China and constructing this artwork and the Xi Jin Pooh artwork related to it can get our members arrested in China.

I also updated to the correct description our members came up with to protest against the Chinese Communist Party

Proof of r/china_place working on the Chained Woman artwork:
https://www.reddit.com/r/ADVChina/comments/twul2e/hi_we_are_the_creators_of_the_chained_woman_and/
https://www.reddit.com/r/Xi_Jin_Pooh/comments/twkfag/thank_you_everyone_especially_the_wonderful_folks/
https://www.reddit.com/r/place/comments/ttrw17/place_for_trafficked_women_in_china_please_dont/
https://www.reddit.com/r/armenia/comments/tuc1tt/hi_rarmenia_were_rchina_place_we_are_focussed_on/

### CODE REVIEW

**Comment by AnonymousRandomPerson** [comment]
Looks like the entire `atlas.json` changed from CRLF line endings to LF line endings. Configure your text editor to output CRLF line endings for this file.

**Comment by AnonymousRandomPerson** [comment]
Resolve merge conflicts.

**Review by AnonymousRandomPerson — CHANGES_REQUESTED** [review]
Address comments.

**Comment by jincha89** [comment]
I didn't change some of the other entries, only the Chained Woman one, not sure why there is a difference

**Review by ab-gh — APPROVED** [review]

**Pull request merged**
