### PR TITLE
tfc: Add Unofficial Corrections canvas revision

### PR DESCRIPTION
**Pull request by bb010g**

### CODE REVIEW

**Comment by mxdanger** [comment]
I'm not a fan of adding it as a timestamp, this should be added as a new variant.

**Comment by AnonymousRandomPerson** [comment]
The latest atlas sync created some merge conflicts.

**Comment by Hans5958** [comment]
> I'm not a fan of adding it as a timestamp, this should be added as a new variant.

Keep in mind that Aria wanted this as a timestamp. https://discord.com/channels/960791635342524496/960792573251833916/1001253343915675649

**Comment by bb010g** [comment]
Rebased on top of the new `atlas.json`. For those curious, I'm just running `%s/"T":/"T:0-1":/g` and `%s/, T":/, T:0-1":/g` in Neovim on the most recent `/web/atlas.json` file.

**Review by AnonymousRandomPerson — APPROVED** [review]

**Pull request merged**
